### ISSUE TITLE
Error when creating new glimmer app: unknown blueprint

### ISSUE THREAD

**Issue by booyaa** [glimmerjs/glimmer-blueprint#17]
## System Details

**npm:** 4.1.2
**ember:** ember-cli: 2.12.1 / node: 7.7.4 os: darwin x64
**yarn:** v0.21.3

## To Reproduce

I've followed the quickstart instructions on the front page: https://www.glimmerjs.com

```
$ yarn global add ember-cli/ember-cli

yarn global v0.21.3
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "ember-cli@2.13.0-beta.2" with binaries:
      - ember
warning No license field
✨  Done in 29.00s.

$ ember new my-app -b @glimmer/blueprint

Unknown blueprint: @glimmer/blueprint
```

**Comment by locks** [comment]
Hey @booyaa, thanks for giving glimmerjs a go :)
If you are getting `ember: ember-cli: 2.12.1` what's likely happening is that you have a global `ember-cli` installed with npm and that's the binary that's actually getting loaded, hence the error.
Can you confirm by running `npm uninstall -g ember-cli`?

**Comment by booyaa** [comment]
I ended up having manually delete the binary from /usr/local/bin! Everything started to work after that! Cheers @locks
