### ISSUE TITLE
Unable to update application

### ISSUE THREAD

**Issue by topaxi** [glimmerjs/glimmer-blueprint#29]
I'm used to update my Ember applications with `ember init` and I'd expect the same to work with glimmer.

I tried running it with `ember init -b @glimmer/blueprint` but all I get is:

```bash
$ ember init -b @glimmer/blueprint
Unknown blueprint: @glimmer/blueprint
```

**Comment by topaxi** [comment]
Ah I just noticed that the blueprint installs `ember-cli@2.12.1` as devDependency, maybe it should use canary too?

**Comment by rwjblue** [comment]
Confirm, would you mind sending in a PR for that?

**Comment by rwjblue** [comment]
Looks like @locks beat you to it in #30
