### ISSUE TITLE
`ember build -prod` fails for master

### ISSUE THREAD

**Issue by mrloop** [glimmerjs/glimmer-blueprint#51]
```
➜  projects node -v
v6.10.3
➜  projects npm install -g ember-cli/ember-cli
/home/ewan/.nvm/versions/node/v6.10.3/bin/🐹 -> /home/ewan/.nvm/versions/node/v6.10.3/lib/node_modules/ember-cli/bin/ember
/home/ewan/.nvm/versions/node/v6.10.3/bin/ember -> /home/ewan/.nvm/versions/node/v6.10.3/lib/node_modules/ember-cli/bin/ember
/home/ewan/.nvm/versions/node/v6.10.3/lib
└─┬ ember-cli@2.14.0-beta.2  (git://github.com/ember-cli/ember-cli.git#79112d64affec417b99e4745d671ff6d615418fe)
  ├── execa@0.7.0
  ├── is-git-url@1.0.0
  └── rsvp@3.6.1

➜  projects ember new glim -b @glimmer/blueprint
installing blueprint
  create .editorconfig
  create .watchmanconfig
  create README.md
  create config/environment.js
  create config/module-map.d.ts
  create config/resolver-configuration.d.ts
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/robots.txt
  create src/index.ts
  create src/main.ts
  create src/ui/components/glim-app/component-test.ts
  create src/ui/components/glim-app/component.ts
  create src/ui/components/glim-app/template.hbs
  create src/ui/index.html
  create src/ui/styles/app.scss
  create src/utils/test-helpers/test-helper.ts
  create testem.json
  create tmp/.metadata_never_index
  create tsconfig.json
  create yarn.lock
Yarn: Installed dependencies
Successfully initialized git.
➜  projects cd glim
➜  glim git:(master) ember build -prod
cleaning up...
Build failed.
The Broccoli Plugin: [Fingerprint] failed with:
SyntaxError: Unexpected token: name (Container)
    at JS_Parse_Error.get (eval at <anonymous> (/home/ewan/projects/glim/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at new BroccoliBuildError (/home/ewan/projects/glim/node_modules/broccoli-builder/lib/broccoli-build-error.js:18:29)
    at /home/ewan/projects/glim/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/home/ewan/projects/glim/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/ewan/projects/glim/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/ewan/projects/glim/node_modules/rsvp/dist/rsvp.js:508:7)
    at publishRejection (/home/ewan/projects/glim/node_modules/rsvp/dist/rsvp.js:443:3)
    at flush (/home/ewan/projects/glim/node_modules/rsvp/dist/rsvp.js:2400:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at:
    at Fingerprint.Plugin (/home/ewan/projects/glim/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/home/ewan/projects/glim/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/home/ewan/projects/glim/node_modules/broccoli-asset-rev/lib/fingerprint.js:27:10)
    at Fingerprint (/home/ewan/projects/glim/node_modules/broccoli-asset-rev/lib/fingerprint.js:22:12)
    at new AssetRev (/home/ewan/projects/glim/node_modules/broccoli-asset-rev/lib/asset-rev.js:27:25)
    at AssetRev (/home/ewan/projects/glim/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/home/ewan/projects/glim/node_modules/broccoli-asset-rev/index.js:31:40)
    at /home/ewan/projects/glim/node_modules/ember-build-utilities/dist/lib/addons/process-tree.js:10:25
    at Array.reduce (native)
    at addonProcessTree (/home/ewan/projects/glim/node_modules/ember-build-utilities/dist/lib/addons/process-tree.js:8:32)
```

**Comment by rwjblue** [comment]
Thank you for reporting! The issue is with the target config (and using uglify which is unaware of ES6 features). A quick work around is to add IE11 to the list of targets (in config/targets.js).

**Comment by mrloop** [comment]
thank you, work around working

**Comment by ve3** [comment]
```
/* eslint-env node */
module.exports = {
  browsers: [
    'ie 9',
    'IE 11',
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
  ]
};
```
`ember build --environment=production`  command return this...

> Build failed.
> The Broccoli Plugin: [Fingerprint] failed with:
> SyntaxError: Unexpected token: punc ())
>     at JS_Parse_Error.get (eval at <anonymous> (C:\wwwroot\rdsadmin\node_modules\uglify-js\tools\node.js:27:1), <anonymous>:86:23)
>     at new BroccoliBuildError (C:\wwwroot\rdsadmin\node_modules\broccoli-builder\lib\broccoli-build-error.js:18:29)
>     at C:\wwwroot\rdsadmin\node_modules\broccoli-builder\lib\builder.js:168:19
>     at tryCatch (C:\wwwroot\rdsadmin\node_modules\rsvp\dist\rsvp.js:525:12)
>     at invokeCallback (C:\wwwroot\rdsadmin\node_modules\rsvp\dist\rsvp.js:538:13)
>     at publish (C:\wwwroot\rdsadmin\node_modules\rsvp\dist\rsvp.js:508:7)
>     at publishRejection (C:\wwwroot\rdsadmin\node_modules\rsvp\dist\rsvp.js:443:3)
>     at flush (C:\wwwroot\rdsadmin\node_modules\rsvp\dist\rsvp.js:2415:5)
>     at _combinedTickCallback (internal/process/next_tick.js:95:7)
>     at process._tickCallback (internal/process/next_tick.js:161:9)
> 
> The broccoli plugin was instantiated at:
>     at Fingerprint.Plugin (C:\wwwroot\rdsadmin\node_modules\broccoli-plugin\index.js:7:31)
>     at Fingerprint.Filter [as constructor] (C:\wwwroot\rdsadmin\node_modules\broccoli-filter\index.js:34:10)
>     at new Fingerprint (C:\wwwroot\rdsadmin\node_modules\broccoli-asset-rev\lib\fingerprint.js:21:10)
>     at Fingerprint (C:\wwwroot\rdsadmin\node_modules\broccoli-asset-rev\lib\fingerprint.js:16:12)
>     at new AssetRev (C:\wwwroot\rdsadmin\node_modules\broccoli-asset-rev\lib\asset-rev.js:31:25)
>     at AssetRev (C:\wwwroot\rdsadmin\node_modules\broccoli-asset-rev\lib\asset-rev.js:7:12)
>     at Class.postprocessTree (C:\wwwroot\rdsadmin\node_modules\broccoli-asset-rev\index.js:31:40)
>     at projectOrAddon.addons.reduce (C:\wwwroot\rdsadmin\node_modules\ember-cli\lib\utilities\addon-process-tree.js:6:25)
>     at Array.reduce (native)
>     at addonProcessTree (C:\wwwroot\rdsadmin\node_modules\ember-cli\lib\utilities\addon-process-tree.js:4:32)


Ember 2.14

**Comment by rwjblue** [comment]
If you update to umber-cli-uglify@^2.0.0-beta.1 it should fix the errors related to newer syntax.

**Comment by ve3** [comment]
Sorry, it is because [js es6 from my js file](https://github.com/emberjs/ember.js/issues/15629).
Remove it and everything works fine.

**Comment by acorncom** [comment]
Looks like this issue can be closed, please speak up if we need it re-opened for any reason

**Comment by mapeveri** [comment]
Hi everyone a have the same problem. This is my target.js

```
/* eslint-env node */
module.exports = {
  browsers: [
    'ie 9',
    'IE 11',
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
  ]
};
```

I have this version of ember-cli-uglify: "ember-cli-uglify": "^2.0.0"

What can I miss?

Thanks!
